window.PROVINCE_CODES = {
  "Navarra": "ES-NA",
  "Barcelona": "ES-B",
  "Castellón": "ES-CS",
  "Zamora": "ES-ZA",
  "Asturias": "ES-O",
  "Orense": "ES-OR",
  "Madrid": "ES-M",
  "Lérida": "ES-L",
  "Jaén": "ES-J",
  "Huelva": "ES-H",
  "Cuenca": "ES-CU",
  "Tarragona": "ES-T",
  "La Coruña": "ES-C",
  "Ávila": "ES-AV",
  "Alicante": "ES-A",
  "Ciudad Real": "ES-CR",
  "Córdoba": "ES-CO",
  "Valladolid": "ES-VA",
  "Santa Cruz de Tenerife": "ES-TF",
  "Zaragoza": "ES-Z",
  "Málaga": "ES-MA",
  "Almería": "ES-AL",
  "Ceuta": "ES-CE",
  "Baleares": "ES-PM",
  "Álava": "ES-VI",
  "Cantabria": "ES-S",
  "Teruel": "ES-TE",
  "Cáceres": "ES-CC",
  "Palencia": "ES-P",
  "Pontevedra": "ES-PO",
  "Las Palmas": "ES-GC",
  "Gerona": "ES-GI",
  "Toledo": "ES-TO",
  "Murcia": "ES-MU",
  "Granada": "ES-GR",
  "Guadalajara": "ES-GU",
  "Albacete": "ES-AB",
  "Soria": "ES-SO",
  "Melilla": "ES-ML",
  "Lugo": "ES-LU",
  "Sevilla": "ES-SE",
  "Cádiz": "ES-CA",
  "Segovia": "ES-SG",
  "Burgos": "ES-BU",
  "Salamanca": "ES-SA",
  "Valencia": "ES-V",
  "León": "ES-LE",
  "Bizkaia": "ES-BI",
  "Huesca": "ES-HU",
  "La Rioja": "ES-LO",
  "Gipuzkoa": "ES-SS",
  "Badajoz": "ES-BA",
  "Ourense": "ES-OR",
  "Lleida": "ES-L",
  "Illes Balears": "ES-PM",
  "Girona": "ES-GI",
  "Vizcaya": "ES-BI",
  "Guipúzcoa": "ES-SS"
};
